#!/bin/bash
awk -F: '($3>=1000){print $1}' /etc/passwd | sort > /root/userlist.txt
echo root >> /root/userlist.txt
for users in $(cat /root/userlist.txt)
do
   echo "$users:Newpassword123@#" | /usr/sbin/chpasswd
   echo "$users's password has been changed"
done
